# Generated by Django 2.2.7 on 2019-11-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('hobbies', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('0', 'Manager'), ('1', 'Employee')], max_length=1)),
                ('profile_picture', models.ImageField(upload_to='profiles/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileManager.Users')),
            ],
        ),
    ]
